const recipes = [
  {
    title: "Matcha Latte",
    image: "img/matcha1.png",
    rating: "4.3",
    prepTime: "10-15 min",
    category: "Drinks",
  },
  {
    title: "Pancakes",
    image: "img/pancakes3.png",
    rating: "4.2",
    prepTime: "10-20 min",
    category: "Desserts",
  },
  {
    title: "Chicken Bowl",
    image: "img/sallad1.png",
    rating: "4.3",
    prepTime: "30 min",
    category: "Rice & Bowls",
  },
  {
    title: "Cookies",
    image: "img/dessert1.png",
    rating: "4.7",
    prepTime: "40 min",
    category: "Desserts",
  },
  {
    title: "Carrot Rice",
    image: "img/CarrotRice.png",
    rating: "4.9",
    prepTime: "20 min",
    category: "Rice & Bowls",
  },
  {
    title: "Blueberry Pie",
    image: "img/BlueberryPie.png",
    rating: "4.7",
    prepTime: "50 min",
    category: "Desserts",
  },
  {
    title: "Egg&Shrimp Noodles",
    image: "img/EggShrimpNoodles.png",
    rating: "4.3",
    prepTime: "30 min",
    category: "Rice & Bowls",
  },
  {
    title: "Flower Mochi",
    image: "img/FlowerMochi.png",
    rating: "4.9",
    prepTime: "60 min",
    category: "Desserts",
  },
  {
    title: "Fried Chicken",
    image: "img/FriedChicken.png",
    rating: "4.9",
    prepTime: "20 min",
    category: "Lunch",
  },
  {
    title: "Kimchi",
    image: "img/Kimchi.png",
    rating: "4.2",
    prepTime: "15 min",
    category: "Lunch",
  },
  {
    title: "Matcha Original",
    image: "img/Matcha2.png",
    rating: "5.0",
    prepTime: "30 min",
    category: "Drinks",
  },
  {
    title: "Black Tea",
    image: "img/tea1.png",
    rating: "4.0",
    prepTime: "5 min",
    category: "Drinks",
  },
  {
    title: "Watermellon Drink",
    image: "img/drink1.png",
    rating: "5.0",
    prepTime: "15 min",
    category: "Drinks",
  },

  {
    title: "Matcha Mochi",
    image: "img/MatchaMochi.png",
    rating: "5.0",
    prepTime: "60 min",
    category: "Desserts",
  },
  {
    title: "Matcha Rolls",
    image: "img/MatchaRolls.png",
    rating: "4.8",
    prepTime: "80 min",
    category: "Desserts",
  },
  {
    title: "Tomato Noodles",
    image: "img/Noodles.png",
    rating: "4.9",
    prepTime: "30 min",
    category: "Rice & Bowls",
  },
  {
    title: "Chicken Noodles",
    image: "img/Noodles2.png",
    rating: "4.7",
    prepTime: "40 min",
    category: "Rice & Bowls",
  },
  {
    title: "Vegetable Noodles",
    image: "img/noodles3.png",
    rating: "4.4",
    prepTime: "20 min",
    category: ["Lunch", "Rice & Bowls"],
  },
  {
    title: "Onion Soup",
    image: "img/OnionSoup.png",
    rating: "4.7",
    prepTime: "40 min",
    category: ["Lunch", "Rice & Bowls"],
  },
  {
    title: "Poke Bowl",
    image: "img/Pokebowl2.png",
    rating: "4.9",
    prepTime: "30 min",
    category: "Lunch",
  },
  {
    title: "Salmon Bowl",
    image: "img/PokebowlSalmon.png",
    rating: "5.0",
    prepTime: "40 min",
    category: ["Lunch", "Rice & Bowls"],
  },
  {
    title: "Egg Ramen",
    image: "img/Ramen1.png",
    rating: "3.2",
    prepTime: "30 min",
    category: ["Lunch", "Rice & Bowls"],
  },
  {
    title: "Lemon Ramen",
    image: "img/Recipes2.png",
    rating: "3.9",
    prepTime: "20 min",
    category: ["Rice & Bowls", "Lunch"],
  },
  {
    title: "Rice Original",
    image: "img/rice.png",
    rating: "5.0",
    prepTime: "15 min",
    category: "Lunch",
  },
  {
    title: "Vegetable Salad",
    image: "img/Sallad2.png",
    rating: "3.0",
    prepTime: "20 min",
    category: "Lunch",
  },
  {
    title: "Pink Salad",
    image: "img/Sallad3.png",
    rating: "3.8",
    prepTime: "25 min",
    category: "Lunch",
  },
  {
    title: "Strawberry Shortcake",
    image: "img/shortcake.png",
    rating: "5.0",
    prepTime: "75 min",
    category: "Desserts",
  },
  {
    title: "Avocado Sushi",
    image: "img/sushi1.png",
    rating: "4.9",
    prepTime: "40 min",
    category: ["Lunch", "Sushi"],
  },
  {
    title: "Cucumber Sushi",
    image: "img/sushi5.png",
    rating: "5.0",
    prepTime: "45 min",
    category: ["Lunch", "Sushi"],
  },
  {
    title: "Fried Sushi",
    image: "img/sushi2.png",
    rating: "4.7",
    prepTime: "45 min",
    category: ["Lunch", "Sushi"],
  },
  {
    title: "Salmon Sushi",
    image: "img/sushi3.png",
    rating: "5.0",
    prepTime: "35 min",
    category: ["Lunch", "Sushi"],
  },
  {
    title: "Cookies",
    image: "img/JapCook.png",
    rating: "5.0",
    prepTime: "85 min",
    category: "Desserts",
  },
];
